inherit_from:
  - '.rubocop_core.yml'

# Put your project-specifc Rubocop config here

Style/ClosingParenthesisIndentation:
  Enabled: false

Style/DotPosition:
  EnforcedStyle: 'trailing'

Style/ExtraSpacing:
  Enabled: false

Style/FileName:
  Exclude:
    - 'lib/ruby-progressbar.rb'

Style/FrozenStringLiteralComment:
  Enabled: false

Style/HashSyntax:
  EnforcedStyle: hash_rockets

Style/IndentationWidth:
  Enabled: false

Style/Lambda:
  Enabled: false

Style/MultilineMethodCallIndentation:
  Enabled: false

Style/NumericPredicate:
  Enabled: false

Style/OptionHash:
  Enabled: false

Style/SymbolArray:
  Enabled: false

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: 'no_comma'

Style/TrailingCommaInLiteral:
  EnforcedStyleForMultiline: 'no_comma'
